In [3]:
from fyers_apiv3.FyersWebsocket import data_ws
from fyers_apiv3 import fyersModel
from datetime import date,datetime, timedelta
import math
import pandas as pd

app_id = open("fyers_appid.txt", 'r').read()
access_token = open("fyers_token.txt", 'r').read()

histdata = pd.DataFrame()

def gethitorydata(st , ed ,res ):
    data = {
    "symbol":"NSE:SBIN-EQ",
    "resolution":str(res),
    "date_format":"1",
    "range_from":st,
    "range_to": ed,
    "cont_flag":"6"
    }
    global histdata
    response = fyers.history(data=data)
    print('Able to fetch 1 Year Data : success')
    #print(response)
    data = pd.DataFrame.from_dict(response['candles'])
    cols = ['datetime', 'open', 'high', 'low', 'close', 'volume']
    data.columns = cols
    data['datetime' ] = pd.to_datetime(data['datetime'], unit="s")
    data['datetime' ] = data['datetime'].dt. tz_localize('utc').dt.tz_convert('Asia/Kolkata')
    data['datetime' ] = data['datetime'].dt. tz_localize(None)
    data = data.set_index('datetime')
    histdata = pd.concat([histdata, data],axis=0)


if __name__ == "__main__":
    token = access_token
    # Initialize the fyersModel instance
    fyers = fyersModel.FyersModel(client_id=app_id, token=access_token)
    start_date = date(2023,1,1)
    end_date = date(2023,3,31)
    print(start_date)
    print(end_date)
    math.ceil(((date.today() - start_date).days)/100)
    
for x in range(4):
    global start_date, end_date
    gethitorydata(start_date, end_date, 5)
    start_date = start_date + timedelta(days=100)
    end_date = start_date + timedelta(days=100)
    
histdata.to_csv("./webinar/sbi_data.csv")

2023-01-01
2023-03-31
Able to fetch 1 Year Data : success
Able to fetch 1 Year Data : success
Able to fetch 1 Year Data : success
Able to fetch 1 Year Data : success

                       open    high     low   close  volume
datetime
2023-01-02 09:15:00  614.95  616.75  614.50  616.00   61614
2023-01-02 09:16:00  615.95  616.45  615.60  615.80   38294
2023-01-02 09:17:00  615.95  615.95  614.40  614.60   66751
2023-01-02 09:18:00  614.65  615.00  614.00  614.45   29757
2023-01-02 09:19:00  614.30  614.65  613.55  613.95   42957
...                     ...     ...     ...     ...     ...
2024-01-25 15:25:00  614.30  614.60  613.30  614.60  270098
2024-01-25 15:26:00  614.55  615.05  614.40  614.75  179817
2024-01-25 15:27:00  614.90  615.50  614.65  615.30  154130
2024-01-25 15:28:00  615.50  617.00  614.45  615.15  409338
2024-01-25 15:29:00  615.30  615.90  613.20  615.00  147298

[98312 rows x 5 columns]